# .mockery.yml
all: false
log-level: info
structname: '{{.InterfaceName}}'
recursive: false

packages:
  github.com/agoda-com/macOS-vz-kubelet/pkg/resource:
    interfaces:
      VirtualMachine:
    config:
      dir: pkg/resource/mocks
      outpkg: mocks
      filename: virtual_machine.go
  github.com/agoda-com/macOS-vz-kubelet/pkg/event:
    interfaces:
      EventRecorder:
    config:
      dir: pkg/event/mocks
      outpkg: mocks
      filename: recorder.go
  github.com/agoda-com/macOS-vz-kubelet/pkg/client:
    interfaces:
      VzClientInterface:
    config:
      dir: pkg/client/mocks
      outpkg: mocks
      filename: client.go
  github.com/agoda-com/macOS-vz-kubelet/pkg/resourcemanager:
    interfaces:
      CLIExecutor:
    config:
      dir: pkg/resourcemanager/mocks
      outpkg: mocks
      filename: cli_executor.go
