// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/virtual-kubelet/virtual-kubelet/node/api"

	io "io"

	mock "github.com/stretchr/testify/mock"

	resource "github.com/agoda-com/macOS-vz-kubelet/pkg/resource"

	resourcemanager "github.com/agoda-com/macOS-vz-kubelet/pkg/resourcemanager"
)

// MockCLIExecutor is an autogenerated mock type for the CLIExecutor type
type MockCLIExecutor struct {
	mock.Mock
}

type MockCLIExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLIExecutor) EXPECT() *MockCLIExecutor_Expecter {
	return &MockCLIExecutor_Expecter{mock: &_m.Mock}
}

// AttachToContainer provides a mock function with given fields: ctx, name, attach
func (_m *MockCLIExecutor) AttachToContainer(ctx context.Context, name string, attach api.AttachIO) error {
	ret := _m.Called(ctx, name, attach)

	if len(ret) == 0 {
		panic("no return value specified for AttachToContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, api.AttachIO) error); ok {
		r0 = rf(ctx, name, attach)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCLIExecutor_AttachToContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachToContainer'
type MockCLIExecutor_AttachToContainer_Call struct {
	*mock.Call
}

// AttachToContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - attach api.AttachIO
func (_e *MockCLIExecutor_Expecter) AttachToContainer(ctx interface{}, name interface{}, attach interface{}) *MockCLIExecutor_AttachToContainer_Call {
	return &MockCLIExecutor_AttachToContainer_Call{Call: _e.mock.On("AttachToContainer", ctx, name, attach)}
}

func (_c *MockCLIExecutor_AttachToContainer_Call) Run(run func(ctx context.Context, name string, attach api.AttachIO)) *MockCLIExecutor_AttachToContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(api.AttachIO))
	})
	return _c
}

func (_c *MockCLIExecutor_AttachToContainer_Call) Return(_a0 error) *MockCLIExecutor_AttachToContainer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCLIExecutor_AttachToContainer_Call) RunAndReturn(run func(context.Context, string, api.AttachIO) error) *MockCLIExecutor_AttachToContainer_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerLogs provides a mock function with given fields: ctx, name, opts
func (_m *MockCLIExecutor) ContainerLogs(ctx context.Context, name string, opts api.ContainerLogOpts) (io.ReadCloser, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for ContainerLogs")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, api.ContainerLogOpts) (io.ReadCloser, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, api.ContainerLogOpts) io.ReadCloser); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, api.ContainerLogOpts) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCLIExecutor_ContainerLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerLogs'
type MockCLIExecutor_ContainerLogs_Call struct {
	*mock.Call
}

// ContainerLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts api.ContainerLogOpts
func (_e *MockCLIExecutor_Expecter) ContainerLogs(ctx interface{}, name interface{}, opts interface{}) *MockCLIExecutor_ContainerLogs_Call {
	return &MockCLIExecutor_ContainerLogs_Call{Call: _e.mock.On("ContainerLogs", ctx, name, opts)}
}

func (_c *MockCLIExecutor_ContainerLogs_Call) Run(run func(ctx context.Context, name string, opts api.ContainerLogOpts)) *MockCLIExecutor_ContainerLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(api.ContainerLogOpts))
	})
	return _c
}

func (_c *MockCLIExecutor_ContainerLogs_Call) Return(_a0 io.ReadCloser, _a1 error) *MockCLIExecutor_ContainerLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCLIExecutor_ContainerLogs_Call) RunAndReturn(run func(context.Context, string, api.ContainerLogOpts) (io.ReadCloser, error)) *MockCLIExecutor_ContainerLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStats provides a mock function with given fields: ctx, id
func (_m *MockCLIExecutor) ContainerStats(ctx context.Context, id string) (uint64, uint64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStats")
	}

	var r0 uint64
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint64, uint64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) uint64); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCLIExecutor_ContainerStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStats'
type MockCLIExecutor_ContainerStats_Call struct {
	*mock.Call
}

// ContainerStats is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCLIExecutor_Expecter) ContainerStats(ctx interface{}, id interface{}) *MockCLIExecutor_ContainerStats_Call {
	return &MockCLIExecutor_ContainerStats_Call{Call: _e.mock.On("ContainerStats", ctx, id)}
}

func (_c *MockCLIExecutor_ContainerStats_Call) Run(run func(ctx context.Context, id string)) *MockCLIExecutor_ContainerStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCLIExecutor_ContainerStats_Call) Return(cpuNano uint64, memBytes uint64, err error) *MockCLIExecutor_ContainerStats_Call {
	_c.Call.Return(cpuNano, memBytes, err)
	return _c
}

func (_c *MockCLIExecutor_ContainerStats_Call) RunAndReturn(run func(context.Context, string) (uint64, uint64, error)) *MockCLIExecutor_ContainerStats_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAndStartContainer provides a mock function with given fields: ctx, args
func (_m *MockCLIExecutor) CreateAndStartContainer(ctx context.Context, args resourcemanager.ContainerCreateArgs) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateAndStartContainer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, resourcemanager.ContainerCreateArgs) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, resourcemanager.ContainerCreateArgs) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, resourcemanager.ContainerCreateArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCLIExecutor_CreateAndStartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAndStartContainer'
type MockCLIExecutor_CreateAndStartContainer_Call struct {
	*mock.Call
}

// CreateAndStartContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - args resourcemanager.ContainerCreateArgs
func (_e *MockCLIExecutor_Expecter) CreateAndStartContainer(ctx interface{}, args interface{}) *MockCLIExecutor_CreateAndStartContainer_Call {
	return &MockCLIExecutor_CreateAndStartContainer_Call{Call: _e.mock.On("CreateAndStartContainer", ctx, args)}
}

func (_c *MockCLIExecutor_CreateAndStartContainer_Call) Run(run func(ctx context.Context, args resourcemanager.ContainerCreateArgs)) *MockCLIExecutor_CreateAndStartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resourcemanager.ContainerCreateArgs))
	})
	return _c
}

func (_c *MockCLIExecutor_CreateAndStartContainer_Call) Return(_a0 string, _a1 error) *MockCLIExecutor_CreateAndStartContainer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCLIExecutor_CreateAndStartContainer_Call) RunAndReturn(run func(context.Context, resourcemanager.ContainerCreateArgs) (string, error)) *MockCLIExecutor_CreateAndStartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNetwork provides a mock function with given fields: ctx, name
func (_m *MockCLIExecutor) CreateNetwork(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateNetwork")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCLIExecutor_CreateNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNetwork'
type MockCLIExecutor_CreateNetwork_Call struct {
	*mock.Call
}

// CreateNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCLIExecutor_Expecter) CreateNetwork(ctx interface{}, name interface{}) *MockCLIExecutor_CreateNetwork_Call {
	return &MockCLIExecutor_CreateNetwork_Call{Call: _e.mock.On("CreateNetwork", ctx, name)}
}

func (_c *MockCLIExecutor_CreateNetwork_Call) Run(run func(ctx context.Context, name string)) *MockCLIExecutor_CreateNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCLIExecutor_CreateNetwork_Call) Return(_a0 error) *MockCLIExecutor_CreateNetwork_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCLIExecutor_CreateNetwork_Call) RunAndReturn(run func(context.Context, string) error) *MockCLIExecutor_CreateNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// ExecInContainer provides a mock function with given fields: ctx, name, cmd, attach
func (_m *MockCLIExecutor) ExecInContainer(ctx context.Context, name string, cmd []string, attach api.AttachIO) error {
	ret := _m.Called(ctx, name, cmd, attach)

	if len(ret) == 0 {
		panic("no return value specified for ExecInContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, api.AttachIO) error); ok {
		r0 = rf(ctx, name, cmd, attach)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCLIExecutor_ExecInContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecInContainer'
type MockCLIExecutor_ExecInContainer_Call struct {
	*mock.Call
}

// ExecInContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - cmd []string
//   - attach api.AttachIO
func (_e *MockCLIExecutor_Expecter) ExecInContainer(ctx interface{}, name interface{}, cmd interface{}, attach interface{}) *MockCLIExecutor_ExecInContainer_Call {
	return &MockCLIExecutor_ExecInContainer_Call{Call: _e.mock.On("ExecInContainer", ctx, name, cmd, attach)}
}

func (_c *MockCLIExecutor_ExecInContainer_Call) Run(run func(ctx context.Context, name string, cmd []string, attach api.AttachIO)) *MockCLIExecutor_ExecInContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(api.AttachIO))
	})
	return _c
}

func (_c *MockCLIExecutor_ExecInContainer_Call) Return(_a0 error) *MockCLIExecutor_ExecInContainer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCLIExecutor_ExecInContainer_Call) RunAndReturn(run func(context.Context, string, []string, api.AttachIO) error) *MockCLIExecutor_ExecInContainer_Call {
	_c.Call.Return(run)
	return _c
}

// InspectContainer provides a mock function with given fields: ctx, id
func (_m *MockCLIExecutor) InspectContainer(ctx context.Context, id string) (resource.ContainerState, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for InspectContainer")
	}

	var r0 resource.ContainerState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (resource.ContainerState, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) resource.ContainerState); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(resource.ContainerState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCLIExecutor_InspectContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectContainer'
type MockCLIExecutor_InspectContainer_Call struct {
	*mock.Call
}

// InspectContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCLIExecutor_Expecter) InspectContainer(ctx interface{}, id interface{}) *MockCLIExecutor_InspectContainer_Call {
	return &MockCLIExecutor_InspectContainer_Call{Call: _e.mock.On("InspectContainer", ctx, id)}
}

func (_c *MockCLIExecutor_InspectContainer_Call) Run(run func(ctx context.Context, id string)) *MockCLIExecutor_InspectContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCLIExecutor_InspectContainer_Call) Return(_a0 resource.ContainerState, _a1 error) *MockCLIExecutor_InspectContainer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCLIExecutor_InspectContainer_Call) RunAndReturn(run func(context.Context, string) (resource.ContainerState, error)) *MockCLIExecutor_InspectContainer_Call {
	_c.Call.Return(run)
	return _c
}

// InspectContainerIP provides a mock function with given fields: ctx, id
func (_m *MockCLIExecutor) InspectContainerIP(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for InspectContainerIP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCLIExecutor_InspectContainerIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectContainerIP'
type MockCLIExecutor_InspectContainerIP_Call struct {
	*mock.Call
}

// InspectContainerIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCLIExecutor_Expecter) InspectContainerIP(ctx interface{}, id interface{}) *MockCLIExecutor_InspectContainerIP_Call {
	return &MockCLIExecutor_InspectContainerIP_Call{Call: _e.mock.On("InspectContainerIP", ctx, id)}
}

func (_c *MockCLIExecutor_InspectContainerIP_Call) Run(run func(ctx context.Context, id string)) *MockCLIExecutor_InspectContainerIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCLIExecutor_InspectContainerIP_Call) Return(_a0 string, _a1 error) *MockCLIExecutor_InspectContainerIP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCLIExecutor_InspectContainerIP_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockCLIExecutor_InspectContainerIP_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function with given fields: ctx, namePrefix
func (_m *MockCLIExecutor) ListContainers(ctx context.Context, namePrefix string) ([]string, error) {
	ret := _m.Called(ctx, namePrefix)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, namePrefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, namePrefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namePrefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCLIExecutor_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockCLIExecutor_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - ctx context.Context
//   - namePrefix string
func (_e *MockCLIExecutor_Expecter) ListContainers(ctx interface{}, namePrefix interface{}) *MockCLIExecutor_ListContainers_Call {
	return &MockCLIExecutor_ListContainers_Call{Call: _e.mock.On("ListContainers", ctx, namePrefix)}
}

func (_c *MockCLIExecutor_ListContainers_Call) Run(run func(ctx context.Context, namePrefix string)) *MockCLIExecutor_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCLIExecutor_ListContainers_Call) Return(_a0 []string, _a1 error) *MockCLIExecutor_ListContainers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCLIExecutor_ListContainers_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockCLIExecutor_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}

// PullImage provides a mock function with given fields: ctx, image, creds
func (_m *MockCLIExecutor) PullImage(ctx context.Context, image string, creds resource.RegistryCredentials) error {
	ret := _m.Called(ctx, image, creds)

	if len(ret) == 0 {
		panic("no return value specified for PullImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, resource.RegistryCredentials) error); ok {
		r0 = rf(ctx, image, creds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCLIExecutor_PullImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullImage'
type MockCLIExecutor_PullImage_Call struct {
	*mock.Call
}

// PullImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - creds resource.RegistryCredentials
func (_e *MockCLIExecutor_Expecter) PullImage(ctx interface{}, image interface{}, creds interface{}) *MockCLIExecutor_PullImage_Call {
	return &MockCLIExecutor_PullImage_Call{Call: _e.mock.On("PullImage", ctx, image, creds)}
}

func (_c *MockCLIExecutor_PullImage_Call) Run(run func(ctx context.Context, image string, creds resource.RegistryCredentials)) *MockCLIExecutor_PullImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(resource.RegistryCredentials))
	})
	return _c
}

func (_c *MockCLIExecutor_PullImage_Call) Return(_a0 error) *MockCLIExecutor_PullImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCLIExecutor_PullImage_Call) RunAndReturn(run func(context.Context, string, resource.RegistryCredentials) error) *MockCLIExecutor_PullImage_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContainer provides a mock function with given fields: ctx, id, force
func (_m *MockCLIExecutor) RemoveContainer(ctx context.Context, id string, force bool) error {
	ret := _m.Called(ctx, id, force)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCLIExecutor_RemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainer'
type MockCLIExecutor_RemoveContainer_Call struct {
	*mock.Call
}

// RemoveContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - force bool
func (_e *MockCLIExecutor_Expecter) RemoveContainer(ctx interface{}, id interface{}, force interface{}) *MockCLIExecutor_RemoveContainer_Call {
	return &MockCLIExecutor_RemoveContainer_Call{Call: _e.mock.On("RemoveContainer", ctx, id, force)}
}

func (_c *MockCLIExecutor_RemoveContainer_Call) Run(run func(ctx context.Context, id string, force bool)) *MockCLIExecutor_RemoveContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockCLIExecutor_RemoveContainer_Call) Return(_a0 error) *MockCLIExecutor_RemoveContainer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCLIExecutor_RemoveContainer_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockCLIExecutor_RemoveContainer_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImage provides a mock function with given fields: ctx, image
func (_m *MockCLIExecutor) RemoveImage(ctx context.Context, image string) error {
	ret := _m.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCLIExecutor_RemoveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImage'
type MockCLIExecutor_RemoveImage_Call struct {
	*mock.Call
}

// RemoveImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
func (_e *MockCLIExecutor_Expecter) RemoveImage(ctx interface{}, image interface{}) *MockCLIExecutor_RemoveImage_Call {
	return &MockCLIExecutor_RemoveImage_Call{Call: _e.mock.On("RemoveImage", ctx, image)}
}

func (_c *MockCLIExecutor_RemoveImage_Call) Run(run func(ctx context.Context, image string)) *MockCLIExecutor_RemoveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCLIExecutor_RemoveImage_Call) Return(_a0 error) *MockCLIExecutor_RemoveImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCLIExecutor_RemoveImage_Call) RunAndReturn(run func(context.Context, string) error) *MockCLIExecutor_RemoveImage_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNetwork provides a mock function with given fields: ctx, name
func (_m *MockCLIExecutor) RemoveNetwork(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNetwork")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCLIExecutor_RemoveNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNetwork'
type MockCLIExecutor_RemoveNetwork_Call struct {
	*mock.Call
}

// RemoveNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCLIExecutor_Expecter) RemoveNetwork(ctx interface{}, name interface{}) *MockCLIExecutor_RemoveNetwork_Call {
	return &MockCLIExecutor_RemoveNetwork_Call{Call: _e.mock.On("RemoveNetwork", ctx, name)}
}

func (_c *MockCLIExecutor_RemoveNetwork_Call) Run(run func(ctx context.Context, name string)) *MockCLIExecutor_RemoveNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCLIExecutor_RemoveNetwork_Call) Return(_a0 error) *MockCLIExecutor_RemoveNetwork_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCLIExecutor_RemoveNetwork_Call) RunAndReturn(run func(context.Context, string) error) *MockCLIExecutor_RemoveNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLIExecutor creates a new instance of MockCLIExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLIExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLIExecutor {
	mock := &MockCLIExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
