// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventRecorder is an autogenerated mock type for the EventRecorder type
type MockEventRecorder struct {
	mock.Mock
}

type MockEventRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRecorder) EXPECT() *MockEventRecorder_Expecter {
	return &MockEventRecorder_Expecter{mock: &_m.Mock}
}

// BackOffPullImage provides a mock function with given fields: ctx, image, containerName, err
func (_m *MockEventRecorder) BackOffPullImage(ctx context.Context, image string, containerName string, err error) {
	_m.Called(ctx, image, containerName, err)
}

// MockEventRecorder_BackOffPullImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackOffPullImage'
type MockEventRecorder_BackOffPullImage_Call struct {
	*mock.Call
}

// BackOffPullImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - containerName string
//   - err error
func (_e *MockEventRecorder_Expecter) BackOffPullImage(ctx interface{}, image interface{}, containerName interface{}, err interface{}) *MockEventRecorder_BackOffPullImage_Call {
	return &MockEventRecorder_BackOffPullImage_Call{Call: _e.mock.On("BackOffPullImage", ctx, image, containerName, err)}
}

func (_c *MockEventRecorder_BackOffPullImage_Call) Run(run func(ctx context.Context, image string, containerName string, err error)) *MockEventRecorder_BackOffPullImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(error))
	})
	return _c
}

func (_c *MockEventRecorder_BackOffPullImage_Call) Return() *MockEventRecorder_BackOffPullImage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_BackOffPullImage_Call) RunAndReturn(run func(context.Context, string, string, error)) *MockEventRecorder_BackOffPullImage_Call {
	_c.Run(run)
	return _c
}

// CreatedContainer provides a mock function with given fields: ctx, containerName
func (_m *MockEventRecorder) CreatedContainer(ctx context.Context, containerName string) {
	_m.Called(ctx, containerName)
}

// MockEventRecorder_CreatedContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatedContainer'
type MockEventRecorder_CreatedContainer_Call struct {
	*mock.Call
}

// CreatedContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
func (_e *MockEventRecorder_Expecter) CreatedContainer(ctx interface{}, containerName interface{}) *MockEventRecorder_CreatedContainer_Call {
	return &MockEventRecorder_CreatedContainer_Call{Call: _e.mock.On("CreatedContainer", ctx, containerName)}
}

func (_c *MockEventRecorder_CreatedContainer_Call) Run(run func(ctx context.Context, containerName string)) *MockEventRecorder_CreatedContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEventRecorder_CreatedContainer_Call) Return() *MockEventRecorder_CreatedContainer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_CreatedContainer_Call) RunAndReturn(run func(context.Context, string)) *MockEventRecorder_CreatedContainer_Call {
	_c.Run(run)
	return _c
}

// FailedPostStartHook provides a mock function with given fields: ctx, containerName, cmd, err
func (_m *MockEventRecorder) FailedPostStartHook(ctx context.Context, containerName string, cmd []string, err error) {
	_m.Called(ctx, containerName, cmd, err)
}

// MockEventRecorder_FailedPostStartHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedPostStartHook'
type MockEventRecorder_FailedPostStartHook_Call struct {
	*mock.Call
}

// FailedPostStartHook is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - cmd []string
//   - err error
func (_e *MockEventRecorder_Expecter) FailedPostStartHook(ctx interface{}, containerName interface{}, cmd interface{}, err interface{}) *MockEventRecorder_FailedPostStartHook_Call {
	return &MockEventRecorder_FailedPostStartHook_Call{Call: _e.mock.On("FailedPostStartHook", ctx, containerName, cmd, err)}
}

func (_c *MockEventRecorder_FailedPostStartHook_Call) Run(run func(ctx context.Context, containerName string, cmd []string, err error)) *MockEventRecorder_FailedPostStartHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(error))
	})
	return _c
}

func (_c *MockEventRecorder_FailedPostStartHook_Call) Return() *MockEventRecorder_FailedPostStartHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_FailedPostStartHook_Call) RunAndReturn(run func(context.Context, string, []string, error)) *MockEventRecorder_FailedPostStartHook_Call {
	_c.Run(run)
	return _c
}

// FailedPreStopHook provides a mock function with given fields: ctx, containerName, cmd, err
func (_m *MockEventRecorder) FailedPreStopHook(ctx context.Context, containerName string, cmd []string, err error) {
	_m.Called(ctx, containerName, cmd, err)
}

// MockEventRecorder_FailedPreStopHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedPreStopHook'
type MockEventRecorder_FailedPreStopHook_Call struct {
	*mock.Call
}

// FailedPreStopHook is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - cmd []string
//   - err error
func (_e *MockEventRecorder_Expecter) FailedPreStopHook(ctx interface{}, containerName interface{}, cmd interface{}, err interface{}) *MockEventRecorder_FailedPreStopHook_Call {
	return &MockEventRecorder_FailedPreStopHook_Call{Call: _e.mock.On("FailedPreStopHook", ctx, containerName, cmd, err)}
}

func (_c *MockEventRecorder_FailedPreStopHook_Call) Run(run func(ctx context.Context, containerName string, cmd []string, err error)) *MockEventRecorder_FailedPreStopHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(error))
	})
	return _c
}

func (_c *MockEventRecorder_FailedPreStopHook_Call) Return() *MockEventRecorder_FailedPreStopHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_FailedPreStopHook_Call) RunAndReturn(run func(context.Context, string, []string, error)) *MockEventRecorder_FailedPreStopHook_Call {
	_c.Run(run)
	return _c
}

// FailedToCreateContainer provides a mock function with given fields: ctx, containerName, err
func (_m *MockEventRecorder) FailedToCreateContainer(ctx context.Context, containerName string, err error) {
	_m.Called(ctx, containerName, err)
}

// MockEventRecorder_FailedToCreateContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToCreateContainer'
type MockEventRecorder_FailedToCreateContainer_Call struct {
	*mock.Call
}

// FailedToCreateContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - err error
func (_e *MockEventRecorder_Expecter) FailedToCreateContainer(ctx interface{}, containerName interface{}, err interface{}) *MockEventRecorder_FailedToCreateContainer_Call {
	return &MockEventRecorder_FailedToCreateContainer_Call{Call: _e.mock.On("FailedToCreateContainer", ctx, containerName, err)}
}

func (_c *MockEventRecorder_FailedToCreateContainer_Call) Run(run func(ctx context.Context, containerName string, err error)) *MockEventRecorder_FailedToCreateContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(error))
	})
	return _c
}

func (_c *MockEventRecorder_FailedToCreateContainer_Call) Return() *MockEventRecorder_FailedToCreateContainer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_FailedToCreateContainer_Call) RunAndReturn(run func(context.Context, string, error)) *MockEventRecorder_FailedToCreateContainer_Call {
	_c.Run(run)
	return _c
}

// FailedToPullImage provides a mock function with given fields: ctx, image, containerName, err
func (_m *MockEventRecorder) FailedToPullImage(ctx context.Context, image string, containerName string, err error) {
	_m.Called(ctx, image, containerName, err)
}

// MockEventRecorder_FailedToPullImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToPullImage'
type MockEventRecorder_FailedToPullImage_Call struct {
	*mock.Call
}

// FailedToPullImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - containerName string
//   - err error
func (_e *MockEventRecorder_Expecter) FailedToPullImage(ctx interface{}, image interface{}, containerName interface{}, err interface{}) *MockEventRecorder_FailedToPullImage_Call {
	return &MockEventRecorder_FailedToPullImage_Call{Call: _e.mock.On("FailedToPullImage", ctx, image, containerName, err)}
}

func (_c *MockEventRecorder_FailedToPullImage_Call) Run(run func(ctx context.Context, image string, containerName string, err error)) *MockEventRecorder_FailedToPullImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(error))
	})
	return _c
}

func (_c *MockEventRecorder_FailedToPullImage_Call) Return() *MockEventRecorder_FailedToPullImage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_FailedToPullImage_Call) RunAndReturn(run func(context.Context, string, string, error)) *MockEventRecorder_FailedToPullImage_Call {
	_c.Run(run)
	return _c
}

// FailedToResolveImagePullSecrets provides a mock function with given fields: ctx, err
func (_m *MockEventRecorder) FailedToResolveImagePullSecrets(ctx context.Context, err error) {
	_m.Called(ctx, err)
}

// MockEventRecorder_FailedToResolveImagePullSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToResolveImagePullSecrets'
type MockEventRecorder_FailedToResolveImagePullSecrets_Call struct {
	*mock.Call
}

// FailedToResolveImagePullSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
func (_e *MockEventRecorder_Expecter) FailedToResolveImagePullSecrets(ctx interface{}, err interface{}) *MockEventRecorder_FailedToResolveImagePullSecrets_Call {
	return &MockEventRecorder_FailedToResolveImagePullSecrets_Call{Call: _e.mock.On("FailedToResolveImagePullSecrets", ctx, err)}
}

func (_c *MockEventRecorder_FailedToResolveImagePullSecrets_Call) Run(run func(ctx context.Context, err error)) *MockEventRecorder_FailedToResolveImagePullSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(error))
	})
	return _c
}

func (_c *MockEventRecorder_FailedToResolveImagePullSecrets_Call) Return() *MockEventRecorder_FailedToResolveImagePullSecrets_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_FailedToResolveImagePullSecrets_Call) RunAndReturn(run func(context.Context, error)) *MockEventRecorder_FailedToResolveImagePullSecrets_Call {
	_c.Run(run)
	return _c
}

// FailedToStartContainer provides a mock function with given fields: ctx, containerName, err
func (_m *MockEventRecorder) FailedToStartContainer(ctx context.Context, containerName string, err error) {
	_m.Called(ctx, containerName, err)
}

// MockEventRecorder_FailedToStartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToStartContainer'
type MockEventRecorder_FailedToStartContainer_Call struct {
	*mock.Call
}

// FailedToStartContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - err error
func (_e *MockEventRecorder_Expecter) FailedToStartContainer(ctx interface{}, containerName interface{}, err interface{}) *MockEventRecorder_FailedToStartContainer_Call {
	return &MockEventRecorder_FailedToStartContainer_Call{Call: _e.mock.On("FailedToStartContainer", ctx, containerName, err)}
}

func (_c *MockEventRecorder_FailedToStartContainer_Call) Run(run func(ctx context.Context, containerName string, err error)) *MockEventRecorder_FailedToStartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(error))
	})
	return _c
}

func (_c *MockEventRecorder_FailedToStartContainer_Call) Return() *MockEventRecorder_FailedToStartContainer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_FailedToStartContainer_Call) RunAndReturn(run func(context.Context, string, error)) *MockEventRecorder_FailedToStartContainer_Call {
	_c.Run(run)
	return _c
}

// FailedToValidateOCI provides a mock function with given fields: ctx, content
func (_m *MockEventRecorder) FailedToValidateOCI(ctx context.Context, content string) {
	_m.Called(ctx, content)
}

// MockEventRecorder_FailedToValidateOCI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToValidateOCI'
type MockEventRecorder_FailedToValidateOCI_Call struct {
	*mock.Call
}

// FailedToValidateOCI is a helper method to define mock.On call
//   - ctx context.Context
//   - content string
func (_e *MockEventRecorder_Expecter) FailedToValidateOCI(ctx interface{}, content interface{}) *MockEventRecorder_FailedToValidateOCI_Call {
	return &MockEventRecorder_FailedToValidateOCI_Call{Call: _e.mock.On("FailedToValidateOCI", ctx, content)}
}

func (_c *MockEventRecorder_FailedToValidateOCI_Call) Run(run func(ctx context.Context, content string)) *MockEventRecorder_FailedToValidateOCI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEventRecorder_FailedToValidateOCI_Call) Return() *MockEventRecorder_FailedToValidateOCI_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_FailedToValidateOCI_Call) RunAndReturn(run func(context.Context, string)) *MockEventRecorder_FailedToValidateOCI_Call {
	_c.Run(run)
	return _c
}

// PulledImage provides a mock function with given fields: ctx, image, containerName, duration
func (_m *MockEventRecorder) PulledImage(ctx context.Context, image string, containerName string, duration string) {
	_m.Called(ctx, image, containerName, duration)
}

// MockEventRecorder_PulledImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PulledImage'
type MockEventRecorder_PulledImage_Call struct {
	*mock.Call
}

// PulledImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - containerName string
//   - duration string
func (_e *MockEventRecorder_Expecter) PulledImage(ctx interface{}, image interface{}, containerName interface{}, duration interface{}) *MockEventRecorder_PulledImage_Call {
	return &MockEventRecorder_PulledImage_Call{Call: _e.mock.On("PulledImage", ctx, image, containerName, duration)}
}

func (_c *MockEventRecorder_PulledImage_Call) Run(run func(ctx context.Context, image string, containerName string, duration string)) *MockEventRecorder_PulledImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockEventRecorder_PulledImage_Call) Return() *MockEventRecorder_PulledImage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_PulledImage_Call) RunAndReturn(run func(context.Context, string, string, string)) *MockEventRecorder_PulledImage_Call {
	_c.Run(run)
	return _c
}

// PullingImage provides a mock function with given fields: ctx, image, containerName
func (_m *MockEventRecorder) PullingImage(ctx context.Context, image string, containerName string) {
	_m.Called(ctx, image, containerName)
}

// MockEventRecorder_PullingImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullingImage'
type MockEventRecorder_PullingImage_Call struct {
	*mock.Call
}

// PullingImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - containerName string
func (_e *MockEventRecorder_Expecter) PullingImage(ctx interface{}, image interface{}, containerName interface{}) *MockEventRecorder_PullingImage_Call {
	return &MockEventRecorder_PullingImage_Call{Call: _e.mock.On("PullingImage", ctx, image, containerName)}
}

func (_c *MockEventRecorder_PullingImage_Call) Run(run func(ctx context.Context, image string, containerName string)) *MockEventRecorder_PullingImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEventRecorder_PullingImage_Call) Return() *MockEventRecorder_PullingImage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_PullingImage_Call) RunAndReturn(run func(context.Context, string, string)) *MockEventRecorder_PullingImage_Call {
	_c.Run(run)
	return _c
}

// StartedContainer provides a mock function with given fields: ctx, containerName
func (_m *MockEventRecorder) StartedContainer(ctx context.Context, containerName string) {
	_m.Called(ctx, containerName)
}

// MockEventRecorder_StartedContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartedContainer'
type MockEventRecorder_StartedContainer_Call struct {
	*mock.Call
}

// StartedContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
func (_e *MockEventRecorder_Expecter) StartedContainer(ctx interface{}, containerName interface{}) *MockEventRecorder_StartedContainer_Call {
	return &MockEventRecorder_StartedContainer_Call{Call: _e.mock.On("StartedContainer", ctx, containerName)}
}

func (_c *MockEventRecorder_StartedContainer_Call) Run(run func(ctx context.Context, containerName string)) *MockEventRecorder_StartedContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEventRecorder_StartedContainer_Call) Return() *MockEventRecorder_StartedContainer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventRecorder_StartedContainer_Call) RunAndReturn(run func(context.Context, string)) *MockEventRecorder_StartedContainer_Call {
	_c.Run(run)
	return _c
}

// NewMockEventRecorder creates a new instance of MockEventRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRecorder {
	mock := &MockEventRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
