// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	client "github.com/agoda-com/macOS-vz-kubelet/pkg/client"
	api "github.com/virtual-kubelet/virtual-kubelet/node/api"

	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"

	resource "github.com/agoda-com/macOS-vz-kubelet/pkg/resource"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/api/core/v1"

	v1alpha1 "k8s.io/kubelet/pkg/apis/stats/v1alpha1"

	volumes "github.com/agoda-com/macOS-vz-kubelet/internal/volumes"
)

// MockVzClientInterface is an autogenerated mock type for the VzClientInterface type
type MockVzClientInterface struct {
	mock.Mock
}

type MockVzClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVzClientInterface) EXPECT() *MockVzClientInterface_Expecter {
	return &MockVzClientInterface_Expecter{mock: &_m.Mock}
}

// AttachToContainer provides a mock function with given fields: ctx, namespace, podName, containerName, attach
func (_m *MockVzClientInterface) AttachToContainer(ctx context.Context, namespace string, podName string, containerName string, attach api.AttachIO) error {
	ret := _m.Called(ctx, namespace, podName, containerName, attach)

	if len(ret) == 0 {
		panic("no return value specified for AttachToContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, api.AttachIO) error); ok {
		r0 = rf(ctx, namespace, podName, containerName, attach)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVzClientInterface_AttachToContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachToContainer'
type MockVzClientInterface_AttachToContainer_Call struct {
	*mock.Call
}

// AttachToContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - podName string
//   - containerName string
//   - attach api.AttachIO
func (_e *MockVzClientInterface_Expecter) AttachToContainer(ctx interface{}, namespace interface{}, podName interface{}, containerName interface{}, attach interface{}) *MockVzClientInterface_AttachToContainer_Call {
	return &MockVzClientInterface_AttachToContainer_Call{Call: _e.mock.On("AttachToContainer", ctx, namespace, podName, containerName, attach)}
}

func (_c *MockVzClientInterface_AttachToContainer_Call) Run(run func(ctx context.Context, namespace string, podName string, containerName string, attach api.AttachIO)) *MockVzClientInterface_AttachToContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(api.AttachIO))
	})
	return _c
}

func (_c *MockVzClientInterface_AttachToContainer_Call) Return(_a0 error) *MockVzClientInterface_AttachToContainer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVzClientInterface_AttachToContainer_Call) RunAndReturn(run func(context.Context, string, string, string, api.AttachIO) error) *MockVzClientInterface_AttachToContainer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVirtualizationGroup provides a mock function with given fields: ctx, pod, volData, creds
func (_m *MockVzClientInterface) CreateVirtualizationGroup(ctx context.Context, pod *v1.Pod, volData *volumes.PodVolumeData, creds resource.RegistryCredentialStore) error {
	ret := _m.Called(ctx, pod, volData, creds)

	if len(ret) == 0 {
		panic("no return value specified for CreateVirtualizationGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Pod, *volumes.PodVolumeData, resource.RegistryCredentialStore) error); ok {
		r0 = rf(ctx, pod, volData, creds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVzClientInterface_CreateVirtualizationGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVirtualizationGroup'
type MockVzClientInterface_CreateVirtualizationGroup_Call struct {
	*mock.Call
}

// CreateVirtualizationGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - pod *v1.Pod
//   - volData *volumes.PodVolumeData
//   - creds resource.RegistryCredentialStore
func (_e *MockVzClientInterface_Expecter) CreateVirtualizationGroup(ctx interface{}, pod interface{}, volData interface{}, creds interface{}) *MockVzClientInterface_CreateVirtualizationGroup_Call {
	return &MockVzClientInterface_CreateVirtualizationGroup_Call{Call: _e.mock.On("CreateVirtualizationGroup", ctx, pod, volData, creds)}
}

func (_c *MockVzClientInterface_CreateVirtualizationGroup_Call) Run(run func(ctx context.Context, pod *v1.Pod, volData *volumes.PodVolumeData, creds resource.RegistryCredentialStore)) *MockVzClientInterface_CreateVirtualizationGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Pod), args[2].(*volumes.PodVolumeData), args[3].(resource.RegistryCredentialStore))
	})
	return _c
}

func (_c *MockVzClientInterface_CreateVirtualizationGroup_Call) Return(_a0 error) *MockVzClientInterface_CreateVirtualizationGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVzClientInterface_CreateVirtualizationGroup_Call) RunAndReturn(run func(context.Context, *v1.Pod, *volumes.PodVolumeData, resource.RegistryCredentialStore) error) *MockVzClientInterface_CreateVirtualizationGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVirtualizationGroup provides a mock function with given fields: ctx, namespace, name, gracePeriod
func (_m *MockVzClientInterface) DeleteVirtualizationGroup(ctx context.Context, namespace string, name string, gracePeriod int64) error {
	ret := _m.Called(ctx, namespace, name, gracePeriod)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVirtualizationGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, namespace, name, gracePeriod)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVzClientInterface_DeleteVirtualizationGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVirtualizationGroup'
type MockVzClientInterface_DeleteVirtualizationGroup_Call struct {
	*mock.Call
}

// DeleteVirtualizationGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
//   - gracePeriod int64
func (_e *MockVzClientInterface_Expecter) DeleteVirtualizationGroup(ctx interface{}, namespace interface{}, name interface{}, gracePeriod interface{}) *MockVzClientInterface_DeleteVirtualizationGroup_Call {
	return &MockVzClientInterface_DeleteVirtualizationGroup_Call{Call: _e.mock.On("DeleteVirtualizationGroup", ctx, namespace, name, gracePeriod)}
}

func (_c *MockVzClientInterface_DeleteVirtualizationGroup_Call) Run(run func(ctx context.Context, namespace string, name string, gracePeriod int64)) *MockVzClientInterface_DeleteVirtualizationGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockVzClientInterface_DeleteVirtualizationGroup_Call) Return(_a0 error) *MockVzClientInterface_DeleteVirtualizationGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVzClientInterface_DeleteVirtualizationGroup_Call) RunAndReturn(run func(context.Context, string, string, int64) error) *MockVzClientInterface_DeleteVirtualizationGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteContainerCommand provides a mock function with given fields: ctx, namespace, podName, containerName, cmd, attach
func (_m *MockVzClientInterface) ExecuteContainerCommand(ctx context.Context, namespace string, podName string, containerName string, cmd []string, attach api.AttachIO) error {
	ret := _m.Called(ctx, namespace, podName, containerName, cmd, attach)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteContainerCommand")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string, api.AttachIO) error); ok {
		r0 = rf(ctx, namespace, podName, containerName, cmd, attach)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVzClientInterface_ExecuteContainerCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteContainerCommand'
type MockVzClientInterface_ExecuteContainerCommand_Call struct {
	*mock.Call
}

// ExecuteContainerCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - podName string
//   - containerName string
//   - cmd []string
//   - attach api.AttachIO
func (_e *MockVzClientInterface_Expecter) ExecuteContainerCommand(ctx interface{}, namespace interface{}, podName interface{}, containerName interface{}, cmd interface{}, attach interface{}) *MockVzClientInterface_ExecuteContainerCommand_Call {
	return &MockVzClientInterface_ExecuteContainerCommand_Call{Call: _e.mock.On("ExecuteContainerCommand", ctx, namespace, podName, containerName, cmd, attach)}
}

func (_c *MockVzClientInterface_ExecuteContainerCommand_Call) Run(run func(ctx context.Context, namespace string, podName string, containerName string, cmd []string, attach api.AttachIO)) *MockVzClientInterface_ExecuteContainerCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]string), args[5].(api.AttachIO))
	})
	return _c
}

func (_c *MockVzClientInterface_ExecuteContainerCommand_Call) Return(_a0 error) *MockVzClientInterface_ExecuteContainerCommand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVzClientInterface_ExecuteContainerCommand_Call) RunAndReturn(run func(context.Context, string, string, string, []string, api.AttachIO) error) *MockVzClientInterface_ExecuteContainerCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainerLogs provides a mock function with given fields: ctx, namespace, podName, containerName, opts
func (_m *MockVzClientInterface) GetContainerLogs(ctx context.Context, namespace string, podName string, containerName string, opts api.ContainerLogOpts) (io.ReadCloser, error) {
	ret := _m.Called(ctx, namespace, podName, containerName, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerLogs")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, api.ContainerLogOpts) (io.ReadCloser, error)); ok {
		return rf(ctx, namespace, podName, containerName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, api.ContainerLogOpts) io.ReadCloser); ok {
		r0 = rf(ctx, namespace, podName, containerName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, api.ContainerLogOpts) error); ok {
		r1 = rf(ctx, namespace, podName, containerName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVzClientInterface_GetContainerLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainerLogs'
type MockVzClientInterface_GetContainerLogs_Call struct {
	*mock.Call
}

// GetContainerLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - podName string
//   - containerName string
//   - opts api.ContainerLogOpts
func (_e *MockVzClientInterface_Expecter) GetContainerLogs(ctx interface{}, namespace interface{}, podName interface{}, containerName interface{}, opts interface{}) *MockVzClientInterface_GetContainerLogs_Call {
	return &MockVzClientInterface_GetContainerLogs_Call{Call: _e.mock.On("GetContainerLogs", ctx, namespace, podName, containerName, opts)}
}

func (_c *MockVzClientInterface_GetContainerLogs_Call) Run(run func(ctx context.Context, namespace string, podName string, containerName string, opts api.ContainerLogOpts)) *MockVzClientInterface_GetContainerLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(api.ContainerLogOpts))
	})
	return _c
}

func (_c *MockVzClientInterface_GetContainerLogs_Call) Return(_a0 io.ReadCloser, _a1 error) *MockVzClientInterface_GetContainerLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVzClientInterface_GetContainerLogs_Call) RunAndReturn(run func(context.Context, string, string, string, api.ContainerLogOpts) (io.ReadCloser, error)) *MockVzClientInterface_GetContainerLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetVirtualizationGroup provides a mock function with given fields: ctx, namespace, name
func (_m *MockVzClientInterface) GetVirtualizationGroup(ctx context.Context, namespace string, name string) (*client.VirtualizationGroup, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetVirtualizationGroup")
	}

	var r0 *client.VirtualizationGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.VirtualizationGroup, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.VirtualizationGroup); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.VirtualizationGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVzClientInterface_GetVirtualizationGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVirtualizationGroup'
type MockVzClientInterface_GetVirtualizationGroup_Call struct {
	*mock.Call
}

// GetVirtualizationGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockVzClientInterface_Expecter) GetVirtualizationGroup(ctx interface{}, namespace interface{}, name interface{}) *MockVzClientInterface_GetVirtualizationGroup_Call {
	return &MockVzClientInterface_GetVirtualizationGroup_Call{Call: _e.mock.On("GetVirtualizationGroup", ctx, namespace, name)}
}

func (_c *MockVzClientInterface_GetVirtualizationGroup_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockVzClientInterface_GetVirtualizationGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockVzClientInterface_GetVirtualizationGroup_Call) Return(_a0 *client.VirtualizationGroup, _a1 error) *MockVzClientInterface_GetVirtualizationGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVzClientInterface_GetVirtualizationGroup_Call) RunAndReturn(run func(context.Context, string, string) (*client.VirtualizationGroup, error)) *MockVzClientInterface_GetVirtualizationGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetVirtualizationGroupListResult provides a mock function with given fields: ctx
func (_m *MockVzClientInterface) GetVirtualizationGroupListResult(ctx context.Context) (map[types.NamespacedName]*client.VirtualizationGroup, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVirtualizationGroupListResult")
	}

	var r0 map[types.NamespacedName]*client.VirtualizationGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[types.NamespacedName]*client.VirtualizationGroup, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[types.NamespacedName]*client.VirtualizationGroup); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.NamespacedName]*client.VirtualizationGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVzClientInterface_GetVirtualizationGroupListResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVirtualizationGroupListResult'
type MockVzClientInterface_GetVirtualizationGroupListResult_Call struct {
	*mock.Call
}

// GetVirtualizationGroupListResult is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVzClientInterface_Expecter) GetVirtualizationGroupListResult(ctx interface{}) *MockVzClientInterface_GetVirtualizationGroupListResult_Call {
	return &MockVzClientInterface_GetVirtualizationGroupListResult_Call{Call: _e.mock.On("GetVirtualizationGroupListResult", ctx)}
}

func (_c *MockVzClientInterface_GetVirtualizationGroupListResult_Call) Run(run func(ctx context.Context)) *MockVzClientInterface_GetVirtualizationGroupListResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockVzClientInterface_GetVirtualizationGroupListResult_Call) Return(_a0 map[types.NamespacedName]*client.VirtualizationGroup, _a1 error) *MockVzClientInterface_GetVirtualizationGroupListResult_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVzClientInterface_GetVirtualizationGroupListResult_Call) RunAndReturn(run func(context.Context) (map[types.NamespacedName]*client.VirtualizationGroup, error)) *MockVzClientInterface_GetVirtualizationGroupListResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetVirtualizationGroupStats provides a mock function with given fields: ctx, pod
func (_m *MockVzClientInterface) GetVirtualizationGroupStats(ctx context.Context, pod *v1.Pod) ([]v1alpha1.ContainerStats, error) {
	ret := _m.Called(ctx, pod)

	if len(ret) == 0 {
		panic("no return value specified for GetVirtualizationGroupStats")
	}

	var r0 []v1alpha1.ContainerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Pod) ([]v1alpha1.ContainerStats, error)); ok {
		return rf(ctx, pod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Pod) []v1alpha1.ContainerStats); ok {
		r0 = rf(ctx, pod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1alpha1.ContainerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Pod) error); ok {
		r1 = rf(ctx, pod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVzClientInterface_GetVirtualizationGroupStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVirtualizationGroupStats'
type MockVzClientInterface_GetVirtualizationGroupStats_Call struct {
	*mock.Call
}

// GetVirtualizationGroupStats is a helper method to define mock.On call
//   - ctx context.Context
//   - pod *v1.Pod
func (_e *MockVzClientInterface_Expecter) GetVirtualizationGroupStats(ctx interface{}, pod interface{}) *MockVzClientInterface_GetVirtualizationGroupStats_Call {
	return &MockVzClientInterface_GetVirtualizationGroupStats_Call{Call: _e.mock.On("GetVirtualizationGroupStats", ctx, pod)}
}

func (_c *MockVzClientInterface_GetVirtualizationGroupStats_Call) Run(run func(ctx context.Context, pod *v1.Pod)) *MockVzClientInterface_GetVirtualizationGroupStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Pod))
	})
	return _c
}

func (_c *MockVzClientInterface_GetVirtualizationGroupStats_Call) Return(_a0 []v1alpha1.ContainerStats, _a1 error) *MockVzClientInterface_GetVirtualizationGroupStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVzClientInterface_GetVirtualizationGroupStats_Call) RunAndReturn(run func(context.Context, *v1.Pod) ([]v1alpha1.ContainerStats, error)) *MockVzClientInterface_GetVirtualizationGroupStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVzClientInterface creates a new instance of MockVzClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVzClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVzClientInterface {
	mock := &MockVzClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
