// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	resource "github.com/agoda-com/macOS-vz-kubelet/pkg/resource"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// MockVirtualMachine is an autogenerated mock type for the VirtualMachine type
type MockVirtualMachine struct {
	mock.Mock
}

type MockVirtualMachine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVirtualMachine) EXPECT() *MockVirtualMachine_Expecter {
	return &MockVirtualMachine_Expecter{mock: &_m.Mock}
}

// Env provides a mock function with no fields
func (_m *MockVirtualMachine) Env() []v1.EnvVar {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Env")
	}

	var r0 []v1.EnvVar
	if rf, ok := ret.Get(0).(func() []v1.EnvVar); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.EnvVar)
		}
	}

	return r0
}

// MockVirtualMachine_Env_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Env'
type MockVirtualMachine_Env_Call struct {
	*mock.Call
}

// Env is a helper method to define mock.On call
func (_e *MockVirtualMachine_Expecter) Env() *MockVirtualMachine_Env_Call {
	return &MockVirtualMachine_Env_Call{Call: _e.mock.On("Env")}
}

func (_c *MockVirtualMachine_Env_Call) Run(run func()) *MockVirtualMachine_Env_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVirtualMachine_Env_Call) Return(_a0 []v1.EnvVar) *MockVirtualMachine_Env_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVirtualMachine_Env_Call) RunAndReturn(run func() []v1.EnvVar) *MockVirtualMachine_Env_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with no fields
func (_m *MockVirtualMachine) Error() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVirtualMachine_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockVirtualMachine_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockVirtualMachine_Expecter) Error() *MockVirtualMachine_Error_Call {
	return &MockVirtualMachine_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockVirtualMachine_Error_Call) Run(run func()) *MockVirtualMachine_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVirtualMachine_Error_Call) Return(_a0 error) *MockVirtualMachine_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVirtualMachine_Error_Call) RunAndReturn(run func() error) *MockVirtualMachine_Error_Call {
	_c.Call.Return(run)
	return _c
}

// FinishedAt provides a mock function with no fields
func (_m *MockVirtualMachine) FinishedAt() *time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FinishedAt")
	}

	var r0 *time.Time
	if rf, ok := ret.Get(0).(func() *time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	return r0
}

// MockVirtualMachine_FinishedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishedAt'
type MockVirtualMachine_FinishedAt_Call struct {
	*mock.Call
}

// FinishedAt is a helper method to define mock.On call
func (_e *MockVirtualMachine_Expecter) FinishedAt() *MockVirtualMachine_FinishedAt_Call {
	return &MockVirtualMachine_FinishedAt_Call{Call: _e.mock.On("FinishedAt")}
}

func (_c *MockVirtualMachine_FinishedAt_Call) Run(run func()) *MockVirtualMachine_FinishedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVirtualMachine_FinishedAt_Call) Return(_a0 *time.Time) *MockVirtualMachine_FinishedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVirtualMachine_FinishedAt_Call) RunAndReturn(run func() *time.Time) *MockVirtualMachine_FinishedAt_Call {
	_c.Call.Return(run)
	return _c
}

// IPAddress provides a mock function with no fields
func (_m *MockVirtualMachine) IPAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IPAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockVirtualMachine_IPAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPAddress'
type MockVirtualMachine_IPAddress_Call struct {
	*mock.Call
}

// IPAddress is a helper method to define mock.On call
func (_e *MockVirtualMachine_Expecter) IPAddress() *MockVirtualMachine_IPAddress_Call {
	return &MockVirtualMachine_IPAddress_Call{Call: _e.mock.On("IPAddress")}
}

func (_c *MockVirtualMachine_IPAddress_Call) Run(run func()) *MockVirtualMachine_IPAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVirtualMachine_IPAddress_Call) Return(_a0 string) *MockVirtualMachine_IPAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVirtualMachine_IPAddress_Call) RunAndReturn(run func() string) *MockVirtualMachine_IPAddress_Call {
	_c.Call.Return(run)
	return _c
}

// SetError provides a mock function with given fields: err
func (_m *MockVirtualMachine) SetError(err error) {
	_m.Called(err)
}

// MockVirtualMachine_SetError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetError'
type MockVirtualMachine_SetError_Call struct {
	*mock.Call
}

// SetError is a helper method to define mock.On call
//   - err error
func (_e *MockVirtualMachine_Expecter) SetError(err interface{}) *MockVirtualMachine_SetError_Call {
	return &MockVirtualMachine_SetError_Call{Call: _e.mock.On("SetError", err)}
}

func (_c *MockVirtualMachine_SetError_Call) Run(run func(err error)) *MockVirtualMachine_SetError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockVirtualMachine_SetError_Call) Return() *MockVirtualMachine_SetError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVirtualMachine_SetError_Call) RunAndReturn(run func(error)) *MockVirtualMachine_SetError_Call {
	_c.Run(run)
	return _c
}

// StartedAt provides a mock function with no fields
func (_m *MockVirtualMachine) StartedAt() *time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartedAt")
	}

	var r0 *time.Time
	if rf, ok := ret.Get(0).(func() *time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	return r0
}

// MockVirtualMachine_StartedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartedAt'
type MockVirtualMachine_StartedAt_Call struct {
	*mock.Call
}

// StartedAt is a helper method to define mock.On call
func (_e *MockVirtualMachine_Expecter) StartedAt() *MockVirtualMachine_StartedAt_Call {
	return &MockVirtualMachine_StartedAt_Call{Call: _e.mock.On("StartedAt")}
}

func (_c *MockVirtualMachine_StartedAt_Call) Run(run func()) *MockVirtualMachine_StartedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVirtualMachine_StartedAt_Call) Return(_a0 *time.Time) *MockVirtualMachine_StartedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVirtualMachine_StartedAt_Call) RunAndReturn(run func() *time.Time) *MockVirtualMachine_StartedAt_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with no fields
func (_m *MockVirtualMachine) State() resource.VirtualMachineState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 resource.VirtualMachineState
	if rf, ok := ret.Get(0).(func() resource.VirtualMachineState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(resource.VirtualMachineState)
	}

	return r0
}

// MockVirtualMachine_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockVirtualMachine_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockVirtualMachine_Expecter) State() *MockVirtualMachine_State_Call {
	return &MockVirtualMachine_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockVirtualMachine_State_Call) Run(run func()) *MockVirtualMachine_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVirtualMachine_State_Call) Return(_a0 resource.VirtualMachineState) *MockVirtualMachine_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVirtualMachine_State_Call) RunAndReturn(run func() resource.VirtualMachineState) *MockVirtualMachine_State_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVirtualMachine creates a new instance of MockVirtualMachine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVirtualMachine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVirtualMachine {
	mock := &MockVirtualMachine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
